wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    code_path: code/pong_training.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1653334656
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 16
      4: 3.8.12
      5: 0.12.7
      8:
      - 4
      - 5
env_name:
  desc: null
  value: Pong-v0
policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 25000
